### ISSUE TITLE
English function?

### ISSUE THREAD

**Issue by ClandestineClout** [shaggyfeng/Obsidian-ZH-Enhanced-Editing-legacy-version#1]
Hi is there any plan to make the plugin in english? Thanks!

**Comment by shaggyfeng** [comment]
Check out the updated version [here](https://github.com/obsidian-canzi/Enhanced-editing)

**Comment by shaggyfeng** [comment]
It should be in English if you selected English in Obsidian. Let me know if it does not work. Thanks
